require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrderableSpecimenController do

  # This should return the minimal set of attributes required to create a valid
  # OrderableSpeciman. As you add validations to OrderableSpeciman, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrderableSpecimenController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all orderable_specimen as @orderable_specimen" do
      orderable_speciman = OrderableSpeciman.create! valid_attributes
      get :index, {}, valid_session
      assigns(:orderable_specimen).should eq([orderable_speciman])
    end
  end

  describe "GET show" do
    it "assigns the requested orderable_speciman as @orderable_speciman" do
      orderable_speciman = OrderableSpeciman.create! valid_attributes
      get :show, {:id => orderable_speciman.to_param}, valid_session
      assigns(:orderable_speciman).should eq(orderable_speciman)
    end
  end

  describe "GET new" do
    it "assigns a new orderable_speciman as @orderable_speciman" do
      get :new, {}, valid_session
      assigns(:orderable_speciman).should be_a_new(OrderableSpeciman)
    end
  end

  describe "GET edit" do
    it "assigns the requested orderable_speciman as @orderable_speciman" do
      orderable_speciman = OrderableSpeciman.create! valid_attributes
      get :edit, {:id => orderable_speciman.to_param}, valid_session
      assigns(:orderable_speciman).should eq(orderable_speciman)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OrderableSpeciman" do
        expect {
          post :create, {:orderable_speciman => valid_attributes}, valid_session
        }.to change(OrderableSpeciman, :count).by(1)
      end

      it "assigns a newly created orderable_speciman as @orderable_speciman" do
        post :create, {:orderable_speciman => valid_attributes}, valid_session
        assigns(:orderable_speciman).should be_a(OrderableSpeciman)
        assigns(:orderable_speciman).should be_persisted
      end

      it "redirects to the created orderable_speciman" do
        post :create, {:orderable_speciman => valid_attributes}, valid_session
        response.should redirect_to(OrderableSpeciman.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved orderable_speciman as @orderable_speciman" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrderableSpeciman.any_instance.stub(:save).and_return(false)
        post :create, {:orderable_speciman => {}}, valid_session
        assigns(:orderable_speciman).should be_a_new(OrderableSpeciman)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrderableSpeciman.any_instance.stub(:save).and_return(false)
        post :create, {:orderable_speciman => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested orderable_speciman" do
        orderable_speciman = OrderableSpeciman.create! valid_attributes
        # Assuming there are no other orderable_specimen in the database, this
        # specifies that the OrderableSpeciman created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OrderableSpeciman.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => orderable_speciman.to_param, :orderable_speciman => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested orderable_speciman as @orderable_speciman" do
        orderable_speciman = OrderableSpeciman.create! valid_attributes
        put :update, {:id => orderable_speciman.to_param, :orderable_speciman => valid_attributes}, valid_session
        assigns(:orderable_speciman).should eq(orderable_speciman)
      end

      it "redirects to the orderable_speciman" do
        orderable_speciman = OrderableSpeciman.create! valid_attributes
        put :update, {:id => orderable_speciman.to_param, :orderable_speciman => valid_attributes}, valid_session
        response.should redirect_to(orderable_speciman)
      end
    end

    describe "with invalid params" do
      it "assigns the orderable_speciman as @orderable_speciman" do
        orderable_speciman = OrderableSpeciman.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrderableSpeciman.any_instance.stub(:save).and_return(false)
        put :update, {:id => orderable_speciman.to_param, :orderable_speciman => {}}, valid_session
        assigns(:orderable_speciman).should eq(orderable_speciman)
      end

      it "re-renders the 'edit' template" do
        orderable_speciman = OrderableSpeciman.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrderableSpeciman.any_instance.stub(:save).and_return(false)
        put :update, {:id => orderable_speciman.to_param, :orderable_speciman => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested orderable_speciman" do
      orderable_speciman = OrderableSpeciman.create! valid_attributes
      expect {
        delete :destroy, {:id => orderable_speciman.to_param}, valid_session
      }.to change(OrderableSpeciman, :count).by(-1)
    end

    it "redirects to the orderable_specimen list" do
      orderable_speciman = OrderableSpeciman.create! valid_attributes
      delete :destroy, {:id => orderable_speciman.to_param}, valid_session
      response.should redirect_to(orderable_specimen_url)
    end
  end

end
