require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrderableConceptsController do

  # This should return the minimal set of attributes required to create a valid
  # OrderableConcept. As you add validations to OrderableConcept, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrderableConceptsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all orderable_concepts as @orderable_concepts" do
      orderable_concept = OrderableConcept.create! valid_attributes
      get :index, {}, valid_session
      assigns(:orderable_concepts).should eq([orderable_concept])
    end
  end

  describe "GET show" do
    it "assigns the requested orderable_concept as @orderable_concept" do
      orderable_concept = OrderableConcept.create! valid_attributes
      get :show, {:id => orderable_concept.to_param}, valid_session
      assigns(:orderable_concept).should eq(orderable_concept)
    end
  end

  describe "GET new" do
    it "assigns a new orderable_concept as @orderable_concept" do
      get :new, {}, valid_session
      assigns(:orderable_concept).should be_a_new(OrderableConcept)
    end
  end

  describe "GET edit" do
    it "assigns the requested orderable_concept as @orderable_concept" do
      orderable_concept = OrderableConcept.create! valid_attributes
      get :edit, {:id => orderable_concept.to_param}, valid_session
      assigns(:orderable_concept).should eq(orderable_concept)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OrderableConcept" do
        expect {
          post :create, {:orderable_concept => valid_attributes}, valid_session
        }.to change(OrderableConcept, :count).by(1)
      end

      it "assigns a newly created orderable_concept as @orderable_concept" do
        post :create, {:orderable_concept => valid_attributes}, valid_session
        assigns(:orderable_concept).should be_a(OrderableConcept)
        assigns(:orderable_concept).should be_persisted
      end

      it "redirects to the created orderable_concept" do
        post :create, {:orderable_concept => valid_attributes}, valid_session
        response.should redirect_to(OrderableConcept.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved orderable_concept as @orderable_concept" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrderableConcept.any_instance.stub(:save).and_return(false)
        post :create, {:orderable_concept => {}}, valid_session
        assigns(:orderable_concept).should be_a_new(OrderableConcept)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrderableConcept.any_instance.stub(:save).and_return(false)
        post :create, {:orderable_concept => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested orderable_concept" do
        orderable_concept = OrderableConcept.create! valid_attributes
        # Assuming there are no other orderable_concepts in the database, this
        # specifies that the OrderableConcept created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OrderableConcept.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => orderable_concept.to_param, :orderable_concept => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested orderable_concept as @orderable_concept" do
        orderable_concept = OrderableConcept.create! valid_attributes
        put :update, {:id => orderable_concept.to_param, :orderable_concept => valid_attributes}, valid_session
        assigns(:orderable_concept).should eq(orderable_concept)
      end

      it "redirects to the orderable_concept" do
        orderable_concept = OrderableConcept.create! valid_attributes
        put :update, {:id => orderable_concept.to_param, :orderable_concept => valid_attributes}, valid_session
        response.should redirect_to(orderable_concept)
      end
    end

    describe "with invalid params" do
      it "assigns the orderable_concept as @orderable_concept" do
        orderable_concept = OrderableConcept.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrderableConcept.any_instance.stub(:save).and_return(false)
        put :update, {:id => orderable_concept.to_param, :orderable_concept => {}}, valid_session
        assigns(:orderable_concept).should eq(orderable_concept)
      end

      it "re-renders the 'edit' template" do
        orderable_concept = OrderableConcept.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrderableConcept.any_instance.stub(:save).and_return(false)
        put :update, {:id => orderable_concept.to_param, :orderable_concept => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested orderable_concept" do
      orderable_concept = OrderableConcept.create! valid_attributes
      expect {
        delete :destroy, {:id => orderable_concept.to_param}, valid_session
      }.to change(OrderableConcept, :count).by(-1)
    end

    it "redirects to the orderable_concepts list" do
      orderable_concept = OrderableConcept.create! valid_attributes
      delete :destroy, {:id => orderable_concept.to_param}, valid_session
      response.should redirect_to(orderable_concepts_url)
    end
  end

end
