require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrderablesController do

  # This should return the minimal set of attributes required to create a valid
  # Orderable. As you add validations to Orderable, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrderablesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all orderables as @orderables" do
      orderable = Orderable.create! valid_attributes
      get :index, {}, valid_session
      assigns(:orderables).should eq([orderable])
    end
  end

  describe "GET show" do
    it "assigns the requested orderable as @orderable" do
      orderable = Orderable.create! valid_attributes
      get :show, {:id => orderable.to_param}, valid_session
      assigns(:orderable).should eq(orderable)
    end
  end

  describe "GET new" do
    it "assigns a new orderable as @orderable" do
      get :new, {}, valid_session
      assigns(:orderable).should be_a_new(Orderable)
    end
  end

  describe "GET edit" do
    it "assigns the requested orderable as @orderable" do
      orderable = Orderable.create! valid_attributes
      get :edit, {:id => orderable.to_param}, valid_session
      assigns(:orderable).should eq(orderable)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Orderable" do
        expect {
          post :create, {:orderable => valid_attributes}, valid_session
        }.to change(Orderable, :count).by(1)
      end

      it "assigns a newly created orderable as @orderable" do
        post :create, {:orderable => valid_attributes}, valid_session
        assigns(:orderable).should be_a(Orderable)
        assigns(:orderable).should be_persisted
      end

      it "redirects to the created orderable" do
        post :create, {:orderable => valid_attributes}, valid_session
        response.should redirect_to(Orderable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved orderable as @orderable" do
        # Trigger the behavior that occurs when invalid params are submitted
        Orderable.any_instance.stub(:save).and_return(false)
        post :create, {:orderable => {}}, valid_session
        assigns(:orderable).should be_a_new(Orderable)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Orderable.any_instance.stub(:save).and_return(false)
        post :create, {:orderable => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested orderable" do
        orderable = Orderable.create! valid_attributes
        # Assuming there are no other orderables in the database, this
        # specifies that the Orderable created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Orderable.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => orderable.to_param, :orderable => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested orderable as @orderable" do
        orderable = Orderable.create! valid_attributes
        put :update, {:id => orderable.to_param, :orderable => valid_attributes}, valid_session
        assigns(:orderable).should eq(orderable)
      end

      it "redirects to the orderable" do
        orderable = Orderable.create! valid_attributes
        put :update, {:id => orderable.to_param, :orderable => valid_attributes}, valid_session
        response.should redirect_to(orderable)
      end
    end

    describe "with invalid params" do
      it "assigns the orderable as @orderable" do
        orderable = Orderable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Orderable.any_instance.stub(:save).and_return(false)
        put :update, {:id => orderable.to_param, :orderable => {}}, valid_session
        assigns(:orderable).should eq(orderable)
      end

      it "re-renders the 'edit' template" do
        orderable = Orderable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Orderable.any_instance.stub(:save).and_return(false)
        put :update, {:id => orderable.to_param, :orderable => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested orderable" do
      orderable = Orderable.create! valid_attributes
      expect {
        delete :destroy, {:id => orderable.to_param}, valid_session
      }.to change(Orderable, :count).by(-1)
    end

    it "redirects to the orderables list" do
      orderable = Orderable.create! valid_attributes
      delete :destroy, {:id => orderable.to_param}, valid_session
      response.should redirect_to(orderables_url)
    end
  end

end
