require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StandardComponentsController do

  # This should return the minimal set of attributes required to create a valid
  # StandardComponent. As you add validations to StandardComponent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StandardComponentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all standard_components as @standard_components" do
      standard_component = StandardComponent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:standard_components).should eq([standard_component])
    end
  end

  describe "GET show" do
    it "assigns the requested standard_component as @standard_component" do
      standard_component = StandardComponent.create! valid_attributes
      get :show, {:id => standard_component.to_param}, valid_session
      assigns(:standard_component).should eq(standard_component)
    end
  end

  describe "GET new" do
    it "assigns a new standard_component as @standard_component" do
      get :new, {}, valid_session
      assigns(:standard_component).should be_a_new(StandardComponent)
    end
  end

  describe "GET edit" do
    it "assigns the requested standard_component as @standard_component" do
      standard_component = StandardComponent.create! valid_attributes
      get :edit, {:id => standard_component.to_param}, valid_session
      assigns(:standard_component).should eq(standard_component)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StandardComponent" do
        expect {
          post :create, {:standard_component => valid_attributes}, valid_session
        }.to change(StandardComponent, :count).by(1)
      end

      it "assigns a newly created standard_component as @standard_component" do
        post :create, {:standard_component => valid_attributes}, valid_session
        assigns(:standard_component).should be_a(StandardComponent)
        assigns(:standard_component).should be_persisted
      end

      it "redirects to the created standard_component" do
        post :create, {:standard_component => valid_attributes}, valid_session
        response.should redirect_to(StandardComponent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved standard_component as @standard_component" do
        # Trigger the behavior that occurs when invalid params are submitted
        StandardComponent.any_instance.stub(:save).and_return(false)
        post :create, {:standard_component => {}}, valid_session
        assigns(:standard_component).should be_a_new(StandardComponent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StandardComponent.any_instance.stub(:save).and_return(false)
        post :create, {:standard_component => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested standard_component" do
        standard_component = StandardComponent.create! valid_attributes
        # Assuming there are no other standard_components in the database, this
        # specifies that the StandardComponent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StandardComponent.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => standard_component.to_param, :standard_component => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested standard_component as @standard_component" do
        standard_component = StandardComponent.create! valid_attributes
        put :update, {:id => standard_component.to_param, :standard_component => valid_attributes}, valid_session
        assigns(:standard_component).should eq(standard_component)
      end

      it "redirects to the standard_component" do
        standard_component = StandardComponent.create! valid_attributes
        put :update, {:id => standard_component.to_param, :standard_component => valid_attributes}, valid_session
        response.should redirect_to(standard_component)
      end
    end

    describe "with invalid params" do
      it "assigns the standard_component as @standard_component" do
        standard_component = StandardComponent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StandardComponent.any_instance.stub(:save).and_return(false)
        put :update, {:id => standard_component.to_param, :standard_component => {}}, valid_session
        assigns(:standard_component).should eq(standard_component)
      end

      it "re-renders the 'edit' template" do
        standard_component = StandardComponent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StandardComponent.any_instance.stub(:save).and_return(false)
        put :update, {:id => standard_component.to_param, :standard_component => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested standard_component" do
      standard_component = StandardComponent.create! valid_attributes
      expect {
        delete :destroy, {:id => standard_component.to_param}, valid_session
      }.to change(StandardComponent, :count).by(-1)
    end

    it "redirects to the standard_components list" do
      standard_component = StandardComponent.create! valid_attributes
      delete :destroy, {:id => standard_component.to_param}, valid_session
      response.should redirect_to(standard_components_url)
    end
  end

end
