require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TrackAssayChangesController do

  # This should return the minimal set of attributes required to create a valid
  # TrackAssayChange. As you add validations to TrackAssayChange, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TrackAssayChangesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all track_assay_changes as @track_assay_changes" do
      track_assay_change = TrackAssayChange.create! valid_attributes
      get :index, {}, valid_session
      assigns(:track_assay_changes).should eq([track_assay_change])
    end
  end

  describe "GET show" do
    it "assigns the requested track_assay_change as @track_assay_change" do
      track_assay_change = TrackAssayChange.create! valid_attributes
      get :show, {:id => track_assay_change.to_param}, valid_session
      assigns(:track_assay_change).should eq(track_assay_change)
    end
  end

  describe "GET new" do
    it "assigns a new track_assay_change as @track_assay_change" do
      get :new, {}, valid_session
      assigns(:track_assay_change).should be_a_new(TrackAssayChange)
    end
  end

  describe "GET edit" do
    it "assigns the requested track_assay_change as @track_assay_change" do
      track_assay_change = TrackAssayChange.create! valid_attributes
      get :edit, {:id => track_assay_change.to_param}, valid_session
      assigns(:track_assay_change).should eq(track_assay_change)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TrackAssayChange" do
        expect {
          post :create, {:track_assay_change => valid_attributes}, valid_session
        }.to change(TrackAssayChange, :count).by(1)
      end

      it "assigns a newly created track_assay_change as @track_assay_change" do
        post :create, {:track_assay_change => valid_attributes}, valid_session
        assigns(:track_assay_change).should be_a(TrackAssayChange)
        assigns(:track_assay_change).should be_persisted
      end

      it "redirects to the created track_assay_change" do
        post :create, {:track_assay_change => valid_attributes}, valid_session
        response.should redirect_to(TrackAssayChange.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved track_assay_change as @track_assay_change" do
        # Trigger the behavior that occurs when invalid params are submitted
        TrackAssayChange.any_instance.stub(:save).and_return(false)
        post :create, {:track_assay_change => {}}, valid_session
        assigns(:track_assay_change).should be_a_new(TrackAssayChange)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TrackAssayChange.any_instance.stub(:save).and_return(false)
        post :create, {:track_assay_change => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested track_assay_change" do
        track_assay_change = TrackAssayChange.create! valid_attributes
        # Assuming there are no other track_assay_changes in the database, this
        # specifies that the TrackAssayChange created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TrackAssayChange.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => track_assay_change.to_param, :track_assay_change => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested track_assay_change as @track_assay_change" do
        track_assay_change = TrackAssayChange.create! valid_attributes
        put :update, {:id => track_assay_change.to_param, :track_assay_change => valid_attributes}, valid_session
        assigns(:track_assay_change).should eq(track_assay_change)
      end

      it "redirects to the track_assay_change" do
        track_assay_change = TrackAssayChange.create! valid_attributes
        put :update, {:id => track_assay_change.to_param, :track_assay_change => valid_attributes}, valid_session
        response.should redirect_to(track_assay_change)
      end
    end

    describe "with invalid params" do
      it "assigns the track_assay_change as @track_assay_change" do
        track_assay_change = TrackAssayChange.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TrackAssayChange.any_instance.stub(:save).and_return(false)
        put :update, {:id => track_assay_change.to_param, :track_assay_change => {}}, valid_session
        assigns(:track_assay_change).should eq(track_assay_change)
      end

      it "re-renders the 'edit' template" do
        track_assay_change = TrackAssayChange.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TrackAssayChange.any_instance.stub(:save).and_return(false)
        put :update, {:id => track_assay_change.to_param, :track_assay_change => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested track_assay_change" do
      track_assay_change = TrackAssayChange.create! valid_attributes
      expect {
        delete :destroy, {:id => track_assay_change.to_param}, valid_session
      }.to change(TrackAssayChange, :count).by(-1)
    end

    it "redirects to the track_assay_changes list" do
      track_assay_change = TrackAssayChange.create! valid_attributes
      delete :destroy, {:id => track_assay_change.to_param}, valid_session
      response.should redirect_to(track_assay_changes_url)
    end
  end

end
